set interfaces bridge br10 member interface bond0.10
set interfaces bridge br10 member interface bond0.20
set interfaces bridge br10 member interface vxlan10
set interfaces bridge br20 member interface vxlan20
set interfaces bridge br30
set interfaces ethernet eth4 hw-id '0c:7d:95:e8:00:02'
set interfaces ethernet eth5 hw-id '0c:7d:95:e8:00:00'
set interfaces ethernet eth6 hw-id '0c:7d:95:e8:00:03'
set interfaces ethernet eth7 hw-id '0c:7d:95:e8:00:01'
set interfaces loopback lo address '10.0.0.2/32'
set interfaces vxlan vxlan10 mtu '1500'
set interfaces vxlan vxlan10 port '4789'
set interfaces vxlan vxlan10 remote '10.0.0.1'
set interfaces vxlan vxlan10 source-address '10.0.0.2'
set interfaces vxlan vxlan10 vlan-to-vni 10 vni '100010'
set interfaces vxlan vxlan10 vni '100010'
set interfaces vxlan vxlan20 mtu '1500'
set interfaces vxlan vxlan20 port '4789'
set interfaces vxlan vxlan20 remote '10.0.0.1'
set interfaces vxlan vxlan20 source-address '10.0.0.2'
set interfaces vxlan vxlan20 vlan-to-vni 20 vni '100020'
set interfaces vxlan vxlan20 vni '100020'
set protocols ospf area 0 network '10.0.0.0/8'
set protocols ospf redistribute connected
set service ntp allow-client address '127.0.0.0/8'
set service ntp allow-client address '169.254.0.0/16'
set service ntp allow-client address '10.0.0.0/8'
set service ntp allow-client address '172.16.0.0/12'
set service ntp allow-client address '192.168.0.0/16'
set service ntp allow-client address '::1/128'
set service ntp allow-client address 'fe80::/10'
set service ntp allow-client address 'fc00::/7'
set service ntp server time1.vyos.net
set service ntp server time2.vyos.net
set service ntp server time3.vyos.net
set system config-management commit-revisions '100'
set system console device ttyS0 speed '115200'
set system host-name 'leaf-2'
set system login user vyos authentication encrypted-password '$6$rounds=656000$4D8xfPqxStExPU7f$XyAj7r0M6T9DBV95oZPWk8p/Dq.trGV4g0rXa.1zHSmSZ66G.a1ZyNSUXaSJCfNWTzBni0wufV/cgF0mAOjNp1'
set system login user vyos authentication plaintext-password ''
set system option reboot-on-upgrade-failure '5'
set system syslog local facility all level 'info'
set system syslog local facility local7 level 'debug'
